# Generated by Django 2.2.7 on 2020-03-11 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_yourself', '0009_auto_20200303_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_yourself.Comment', verbose_name='Comments'),
        ),
    ]
