# Generated by Django 2.2.7 on 2020-03-15 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_yourself', '0011_remove_answer_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_yourself.Question', verbose_name='Question_comment'),
        ),
    ]
